name: Build and Publish

on:
  # run it on push to the default repository branch
  push:
    branches: [ master ]
  # run it during pull request
  pull_request:

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install NPM Dependencies
        run: npm ci

      - name: Shadowbox Docker Build
        env:
          ARCH: arm64
          SB_IMAGE: ghcr.io/zagirnur/vpn-provider-outline:latest
        run: npm run action shadowbox/docker/build

      - name: Build image and push to Docker Hub and GitHub Container Registry
        run: docker push ghcr.io/zagirnur/vpn-provider-outline:latest