name: Build and Test

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - master

jobs:
  shadowbox:
    name: Shadowbox
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install NPM Dependencies
        run: npm ci

      - name: Shadowbox Docker Build
        env:
          ARCH: arm64
          SB_IMAGE: ghcr.io/zagirnur/vpn-provider-outline:latest
        run: npm run action shadowbox/docker/build

      - name: Build image and push to Docker Hub and GitHub Container Registry
        run: docker push ghcr.io/zagirnur/vpn-provider-outline:latest